#!/usr/bin/env bash

echo "running pre-commit hook"
# echo "arguments = $@"

# redirect all output to stderr
exec 1>&2

# only run pipeline if any cpp src/unit test is staged
# modified_sources=$(git --no-pager diff --staged --name-only src/ tests/unit_tests/) # returns one file per line
# echo "modified_sources = $modified_sources"
# if [ -z "$modified_sources" ]; then
#     exit 0
# fi

# for filename in "$modified_sources" ; do # won't work
# echo "$modified_sources" | while read filename ; do # iterates on lines
#     if [[ "$filename" =~ \.(h|hpp|cpp)$ ]] ; then
#         echo "yes! $filename is cpp"
#     else
#         echo "no, skipping $filename"
#     fi
# done

scripts/pipeline.sh --all release
result=$?
if [ $result -ne 0 ] ; then
    exit $result
fi

exit 23

exit 0